# versao docker-compose
version: '3.8'

services:
  # Contêiner 1: Banco de Dados
  db:
    # Versao do postgres utilizada
    image: postgres:15-alpine
    container_name: safestreets_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: safestreets
    ports:
      # porta padrao do postgres
      - "5432:5432"
    volumes:
      # onde o volume docker sera armazenado
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d safestreets"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Contêiner 2: Backend FastAPI
  api:
    build: .
    container_name: safestreets_api
    environment:
      DATABASE_URL: postgresql://admin:123@db:5432/safestreets
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    # Aplica as migrations (cria as tabelas) antes de subir o servidor.
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

# criacao do volume para o banco de dados
volumes:
  postgres_data: